// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5X6Y6mwjKSwrzojAvEMBXWGeOmOiP2fs',
    appId: '1:926534351827:web:c19de8207209fb2e444d26',
    messagingSenderId: '926534351827',
    projectId: 'personalfirebasecrud',
    authDomain: 'personalfirebasecrud.firebaseapp.com',
    storageBucket: 'personalfirebasecrud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQc5FYdD29wDxt8RlRPP6zAtvPbNYN0Sg',
    appId: '1:926534351827:android:08c873ad31b23068444d26',
    messagingSenderId: '926534351827',
    projectId: 'personalfirebasecrud',
    storageBucket: 'personalfirebasecrud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjSVghCDa-C8a9iuKuoBewnL0Tjg6qU6g',
    appId: '1:926534351827:ios:ba8f57830512a2f5444d26',
    messagingSenderId: '926534351827',
    projectId: 'personalfirebasecrud',
    storageBucket: 'personalfirebasecrud.appspot.com',
    iosClientId: '926534351827-aq0dsnhv38jehe55q9taekh6spsvluai.apps.googleusercontent.com',
    iosBundleId: 'com.flutterkage2k.personalfirebasecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjSVghCDa-C8a9iuKuoBewnL0Tjg6qU6g',
    appId: '1:926534351827:ios:ba8f57830512a2f5444d26',
    messagingSenderId: '926534351827',
    projectId: 'personalfirebasecrud',
    storageBucket: 'personalfirebasecrud.appspot.com',
    iosClientId: '926534351827-aq0dsnhv38jehe55q9taekh6spsvluai.apps.googleusercontent.com',
    iosBundleId: 'com.flutterkage2k.personalfirebasecrud',
  );
}
